### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by shidilrzf** [mdiephuis/information-bottleneck-gan#1]
## Priority:
 -  [ ] check the channel
## Others
-  [ ] save model weights
 -  [x] add data augmentation
 -  [ ] add tqm
 -  [ ] check ring data
